package org.icij.extract.document;

import java.net.URI;
import java.nio.charset.Charset;
import java.nio.file.Path;
import java.time.Duration;
import java.util.HashMap;
import java.util.Map;
import org.icij.task.Options;

// generated by OptionsRecordGenerator from org.icij.extract.document.DocumentFactory
public record DocumentFactoryOptions(
        // Set the output encoding for text and document attributes. Defaults to UTF-8.
        String charset,
        // For calculating document ID digests, where applicable depending on the ID method.
        String digestAlgorithm,
        // The method for determining document IDs, for queues that use them. Defaults to using the path as an ID.
        String idMethod,
        // Optional parameter to specify the language of the document.
        String language) {

    public static DocumentFactoryOptions from(Options<String> options) {
        return new DocumentFactoryOptions(
                options.valueIfPresent("charset").orElse(null),
                options.valueIfPresent("digestAlgorithm").orElse(null),
                options.valueIfPresent("idMethod").orElse(null),
                options.valueIfPresent("language").orElse(null));
    }

    public Options<String> toOptions() {
        Map<String, Object> map = new HashMap<>();
        if (charset != null) map.put("charset", String.valueOf(charset));
        if (digestAlgorithm != null) map.put("digestAlgorithm", String.valueOf(digestAlgorithm));
        if (idMethod != null) map.put("idMethod", String.valueOf(idMethod));
        if (language != null) map.put("language", String.valueOf(language));
        return Options.from(map);
    }
}
