package org.icij.extract.extractor;

import java.nio.file.Path;
import java.time.Duration;
import java.util.HashMap;
import java.util.Map;
import org.icij.task.Options;

// generated by OptionsRecordGenerator from org.icij.extract.extractor.Extractor
public record ExtractorOptions(
        // The hash digest method used for documents, for example "SHA256".
        String digestAlgorithm,
        // Include the given project name in the document hash.
        String digestProjectName,
        // Set the embed handling mode. Either "ignore", "concatenate" or "spawn". When set to concatenate, embeds
        // are parsed and the output is in-lined into the main output.Defaults to spawning, which spawns new
        // documents for each embedded document encountered.
        String embedHandling,
        // Maximum megabytes of embedded-document extracted text to hold in memory before overflowing to temp files.
        // Defaults to 64.
        String embedMemoryBudgetMb,
        // Heap occupancy ratio (0-1) above which embedded-document text spills to temp files early, regardless of
        // the byte budget, to keep extraction within the available heap on very large containers. Defaults to 0.7;
        // set to 0 or 1 to disable.
        String embedMemoryPressureThreshold,
        // Path to a directory for outputting attachments en masse.
        Path embedOutput,
        // Name nameless non-inline embeds with the pre-9.x global untitled_N counter instead of the per-parent
        // scheme, for on-demand resolution of corpora indexed before the per-parent change. Serial mode only.
        String legacyUntitledNaming,
        // Maximum nesting depth of embedded documents to descend into. Embeds deeper than this are skipped
        // (recorded, not parsed) to guard against decompression-bomb archives. Defaults to 20. Set to 0 to disable.
        String maxEmbedDepth,
        // Maximum declared decompressed size, in bytes, of a single embedded document to descend into. Embeds larger
        // than this are skipped (recorded, not parsed) to guard against decompression-bomb archives whose entries
        // expand to multi-GiB. Only enforced when the embed's size is known. Disabled by default (0). Set to a
        // positive byte count to enable.
        String maxEmbedSizeBytes,
        // Enable or disable automatic OCR. On by default.
        String ocr,
        // Output path for OCR cache files.
        Path ocrCache,
        // Enable parallel OCR fan-out for image attachments. On by default. When off, images OCR inline on the parse
        // thread.
        String ocrFanout,
        // Set the languages used by Tesseract. Multiple languages may be specified, separated by plus characters.
        // Tesseract uses 3-character ISO 639-2 language codes.
        String ocrLanguage,
        // Image embeds smaller than this many bytes OCR inline instead of via the pool. Defaults to 0 (always fan out).
        String ocrMinImageBytes,
        // Number of OCR tasks run in parallel across all extraction threads. Defaults to the number of available
        // processors. Set to 1 for serial OCR.
        String ocrParallelism,
        // Set the PDF OCR strategy. One of "NO_OCR" (default), "AUTO", "OCR_AND_TEXT_EXTRACTION" or "OCR_ONLY". Any
        // rendering strategy OCRs whole pages and disables inline-image extraction, which is required to correctly
        // extract scanned/MRC PDFs. Defaults to NO_OCR.
        String ocrStrategy,
        // Set the timeout for the Tesseract process to finish e.g. "5s" or "1m". Defaults to 12 hours.
        Duration ocrTimeout,
        // Name of the OCR to use TESSERACT, TESS4J
        String ocrType,
        // Set the output format. Either "text" or "HTML". Defaults to text output.
        String outputFormat,
        // Wall-clock timeout for a single document's parse and output, e.g. "30m" or "24h". Set to 0 to disable.
        // Defaults to 24h.
        Duration parseTimeout,
        // Interval between extraction progress heartbeat log lines, e.g. "60s". Set to 0 to disable. Defaults to 60s.
        Duration progressHeartbeatInterval,
        // Parse the folders of a single PST/OST mailbox in parallel across a shared bounded pool, instead of one
        // thread per file. Embed ids, digests and artifact filenames are byte-identical to the serial walk.
        String pstFolderFanout,
        // Number of PST/OST folder-walk tasks run in parallel across all in-flight mailboxes. Separate from
        // ocrParallelism.
        String pstParseParallelism,
        // Maximum number of parsed-but-not-yet-written embedded documents held in the streaming-spew queue before
        // the parse thread blocks (backpressure). Defaults to 1000.
        String spewQueueCapacity,
        // Write embedded documents to the spewer as they are parsed, instead of buffering the whole tree and writing
        // it afterwards. On by default; set to false to fall back to the legacy buffer-then-walk path.
        String streamingSpew) {
    public static ExtractorOptions from(Options<String> options) {
        return new ExtractorOptions(options.valueIfPresent("digestAlgorithm").orElse(null),
                                    options.valueIfPresent("digestProjectName").orElse(null),
                                    options.valueIfPresent("embedHandling").orElse(null),
                                    options.valueIfPresent("embedMemoryBudgetMb").orElse(null),
                                    options.valueIfPresent("embedMemoryPressureThreshold").orElse(null),
                                    options.ifPresent("embedOutput", o -> o.parse().asPath()).orElse(null),
                                    options.valueIfPresent("legacyUntitledNaming").orElse(null),
                                    options.valueIfPresent("maxEmbedDepth").orElse(null),
                                    options.valueIfPresent("maxEmbedSizeBytes").orElse(null),
                                    options.valueIfPresent("ocr").orElse(null),
                                    options.ifPresent("ocrCache", o -> o.parse().asPath()).orElse(null),
                                    options.valueIfPresent("ocrFanout").orElse(null),
                                    options.valueIfPresent("ocrLanguage").orElse(null),
                                    options.valueIfPresent("ocrMinImageBytes").orElse(null),
                                    options.valueIfPresent("ocrParallelism").orElse(null),
                                    options.valueIfPresent("ocrStrategy").orElse(null),
                                    options.ifPresent("ocrTimeout", o -> o.parse().asDuration()).orElse(null),
                                    options.valueIfPresent("ocrType").orElse(null),
                                    options.valueIfPresent("outputFormat").orElse(null),
                                    options.ifPresent("parseTimeout", o -> o.parse().asDuration()).orElse(null),
                                    options.ifPresent("progressHeartbeatInterval", o -> o.parse().asDuration())
                                           .orElse(null), options.valueIfPresent("pstFolderFanout").orElse(null),
                                    options.valueIfPresent("pstParseParallelism").orElse(null),
                                    options.valueIfPresent("spewQueueCapacity").orElse(null),
                                    options.valueIfPresent("streamingSpew").orElse(null));
    }

    public Options<String> toOptions() {
        Map<String, Object> map = new HashMap<>();
        if (digestAlgorithm != null) {map.put("digestAlgorithm", String.valueOf(digestAlgorithm));}
        if (digestProjectName != null) {map.put("digestProjectName", String.valueOf(digestProjectName));}
        if (embedHandling != null) {map.put("embedHandling", String.valueOf(embedHandling));}
        if (embedMemoryBudgetMb != null) {map.put("embedMemoryBudgetMb", String.valueOf(embedMemoryBudgetMb));}
        if (embedMemoryPressureThreshold != null) {
            map.put("embedMemoryPressureThreshold", String.valueOf(embedMemoryPressureThreshold));
        }
        if (embedOutput != null) {map.put("embedOutput", String.valueOf(embedOutput));}
        if (legacyUntitledNaming != null) {map.put("legacyUntitledNaming", String.valueOf(legacyUntitledNaming));}
        if (maxEmbedDepth != null) {map.put("maxEmbedDepth", String.valueOf(maxEmbedDepth));}
        if (maxEmbedSizeBytes != null) {map.put("maxEmbedSizeBytes", String.valueOf(maxEmbedSizeBytes));}
        if (ocr != null) {map.put("ocr", String.valueOf(ocr));}
        if (ocrCache != null) {map.put("ocrCache", String.valueOf(ocrCache));}
        if (ocrFanout != null) {map.put("ocrFanout", String.valueOf(ocrFanout));}
        if (ocrLanguage != null) {map.put("ocrLanguage", String.valueOf(ocrLanguage));}
        if (ocrMinImageBytes != null) {map.put("ocrMinImageBytes", String.valueOf(ocrMinImageBytes));}
        if (ocrParallelism != null) {map.put("ocrParallelism", String.valueOf(ocrParallelism));}
        if (ocrStrategy != null) {map.put("ocrStrategy", String.valueOf(ocrStrategy));}
        if (ocrTimeout != null) {map.put("ocrTimeout", ocrTimeout.toMillis() + "ms");}
        if (ocrType != null) {map.put("ocrType", String.valueOf(ocrType));}
        if (outputFormat != null) {map.put("outputFormat", String.valueOf(outputFormat));}
        if (parseTimeout != null) {map.put("parseTimeout", parseTimeout.toMillis() + "ms");}
        if (progressHeartbeatInterval != null) {
            map.put("progressHeartbeatInterval", progressHeartbeatInterval.toMillis() + "ms");
        }
        if (pstFolderFanout != null) {map.put("pstFolderFanout", String.valueOf(pstFolderFanout));}
        if (pstParseParallelism != null) {map.put("pstParseParallelism", String.valueOf(pstParseParallelism));}
        if (spewQueueCapacity != null) {map.put("spewQueueCapacity", String.valueOf(spewQueueCapacity));}
        if (streamingSpew != null) {map.put("streamingSpew", String.valueOf(streamingSpew));}
        return Options.from(map);
    }
}
