package org.icij.task;

import java.io.IOException;
import java.nio.file.FileAlreadyExistsException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardOpenOption;
import java.util.Comparator;
import java.util.List;
import java.util.Map;
import java.util.stream.StreamSupport;

import static java.util.stream.Collectors.joining;
import static java.util.stream.Collectors.toList;
import org.icij.task.annotation.OptionsClass;

/**
 * Prints the source of a record mirroring the {@link org.icij.task.annotation.Option}s declared by a class
 * (and, recursively, by its {@link org.icij.task.annotation.OptionsClass}es).
 * <p>
 * The field type is the option's {@code parameter} with its first letter uppercased, when it is a type
 * {@link OptionParser} can parse; otherwise it is {@code String}. Fields are nullable: {@code null} means
 * the option is absent. The output is a scaffold meant to be committed and edited by hand.
 * <p>
 * Usage: {@code java -cp ... org.icij.task.OptionsRecordGenerator <class name> [source dir]}: prints the record,
 * or writes it in the source dir (never overwriting). From maven:
 * {@code mvn -pl extract-lib compile exec:java@generate-options -Doptions.class=<class name>}
 */
public class OptionsRecordGenerator {
    // type -> OptionParser method
    private static final Map<String, String> KNOWN_TYPES = Map.of(
            "Duration", "asDuration", "Path", "asPath", "URI", "asURI",
            "Charset", "asCharset", "Integer", "asInteger", "Boolean", "asBoolean");

    public static void main(String[] args) throws ClassNotFoundException, IOException {
        if (args.length < 1) {
            System.err.println("usage: OptionsRecordGenerator <class name> [source dir]");
            System.exit(1);
        }
        Class<?> clazz = Class.forName(args[0]);
        if (args.length > 1) {
            System.out.println("generated " + write(clazz, Paths.get(args[1])));
        } else {
            System.out.print(generate(clazz, recordName(clazz)));
        }
    }

    /**
     * Writes the {@code <SimpleName>Options} record in {@code srcDir}, under the package of {@code clazz}.
     *
     * @throws FileAlreadyExistsException if the record exists: it may have been edited by hand
     */
    public static Path write(Class<?> clazz, Path srcDir) throws IOException {
        Path file = srcDir.resolve(clazz.getPackageName().replace('.', '/')).resolve(recordName(clazz) + ".java");
        Files.createDirectories(file.getParent());
        return Files.writeString(file, generate(clazz, recordName(clazz)), StandardOpenOption.CREATE_NEW);
    }

    private static String recordName(Class<?> clazz) {
        return clazz.getSimpleName() + "Options";
    }

    public static String generate(Class<?> clazz, String recordName) {
        Options<String> declared = new Options<>();
        for (org.icij.task.annotation.Option option : clazz.getAnnotationsByType(org.icij.task.annotation.Option.class)) {
            declared.add(option, StringOptionParser::new);
        }
        for (OptionsClass other : clazz.getAnnotationsByType(OptionsClass.class)) {
            declared.add(other, StringOptionParser::new);
        }
        // Options is backed by a HashMap: sort for a stable output
        List<Option<String>> options = StreamSupport.stream(declared.spliterator(), false)
                .sorted(Comparator.comparing(Option::name)).collect(toList());

        String fields = options.stream().map(o -> String.format("        // %s\n        %s %s",
                o.description().replaceAll("\\s+", " "), type(o), o.name())).collect(joining(",\n"));
        String fromArgs = options.stream().map(o -> KNOWN_TYPES.containsKey(type(o)) ?
                String.format("                options.ifPresent(\"%s\", o -> o.parse().%s()).orElse(null)", o.name(), KNOWN_TYPES.get(type(o))) :
                String.format("                options.valueIfPresent(\"%s\").orElse(null)", o.name())).collect(joining(",\n"));
        String puts = options.stream().map(o -> String.format("        if (%1$s != null) map.put(\"%1$s\", %2$s);",
                o.name(), "Duration".equals(type(o)) ? o.name() + ".toMillis() + \"ms\"" : "String.valueOf(" + o.name() + ")"))
                .collect(joining("\n"));

        return "package " + clazz.getPackageName() + ";\n\n" +
                "import java.net.URI;\n" +
                "import java.nio.charset.Charset;\n" +
                "import java.nio.file.Path;\n" +
                "import java.time.Duration;\n" +
                "import java.util.HashMap;\n" +
                "import java.util.Map;\n" +
                "import org.icij.task.Options;\n\n" +
                "// generated by OptionsRecordGenerator from " + clazz.getName() + "\n" +
                "public record " + recordName + "(\n" + fields + ") {\n\n" +
                "    public static " + recordName + " from(Options<String> options) {\n" +
                "        return new " + recordName + "(\n" + fromArgs + ");\n" +
                "    }\n\n" +
                "    public Options<String> toOptions() {\n" +
                "        Map<String, Object> map = new HashMap<>();\n" + puts + "\n" +
                "        return Options.from(map);\n" +
                "    }\n" +
                "}\n";
    }

    private static String type(Option<String> option) {
        String parameter = option.parameter();
        String type = parameter == null || parameter.isEmpty() ? "" :
                Character.toUpperCase(parameter.charAt(0)) + parameter.substring(1);
        return KNOWN_TYPES.containsKey(type) ? type : "String";
    }
}
